# Generated by Django 3.0.7 on 2020-06-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0003_delete_tomcate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
