# Generated by Django 3.0.7 on 2020-06-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0004_auto_20200609_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
